/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveGameModal: typeof import('./components/ActiveGameModal.vue')['default']
    ActiveGames: typeof import('./components/ActiveGames.vue')['default']
    AddActivePlayer: typeof import('./components/AddActivePlayer.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FinishGameForPlayerModal: typeof import('./components/FinishGameForPlayerModal.vue')['default']
    HistoricalGames: typeof import('./components/HistoricalGames.vue')['default']
    Players: typeof import('./components/Players.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/Tabs.vue')['default']
  }
}
